In [1]:
### By using the Keras Libraray

In [2]:
import numpy as np
import pandas as pd


In [3]:
## After that creating our own dataset
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['CGPA','PROFILE_SCORE','LPA'])

In [4]:
## Now see our dataset
df.head()

,CGPA,PROFILE_SCORE,LPA
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [5]:
## Now the next imp part , importing the keras library
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [6]:
## Now storing object into variable
model = Sequential()
model.add(Dense(2,activation='linear', input_dim=2)) ## This is the input layer 
model.add(Dense(1,activation='linear'))
import warnings
warnings.filterwarnings('ignore')

D:\Anaconda\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.get_weights()

[array([[ 0.41847444, -0.4786458 ],
        [ 1.0497307 , -0.78610337]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.2305437 ],
        [-0.76711005]], dtype=float32),
 array([0.], dtype=float32)]

In [9]:
new_weights=[np.array([[0.1,0.1],
                     [0.1,0.1]], dtype=np.float32),
            np.array([0.,0.], dtype=np.float32),
            np.array([[0.1],[0.1]], dtype=np.float32),
            np.array([0.], dtype=np.float32)]

In [10]:
model.set_weights(new_weights)

In [11]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss="mean_squared_error", optimizer=optimizer)

In [13]:
model.fit(df.iloc[:,0:-1].values, df['LPA'].values, epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 27.9075
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 27.5885
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 27.2733
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 26.9405
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 26.5886 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 26.2328
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 25.8381
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 25.4670
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 25.1054
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 24.6995 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 24.2411
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 23.8467
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 23.3938 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 22.9659 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 22.5279
Epoch 16/75
4/4

In [14]:
model.get_weights()

[array([[0.3735835 , 0.3735835 ],
        [0.36534044, 0.36534044]], dtype=float32),
 array([0.27215952, 0.27215952], dtype=float32),
 array([[0.37274757],
        [0.37274757]], dtype=float32),
 array([0.20448948], dtype=float32)]