In [1]:
### By using the Keras Libraray

In [2]:
import numpy as np
import pandas as pd


In [3]:
## After that creating our own dataset
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['CGPA','PROFILE_SCORE','LPA'])

In [4]:
## Now see our dataset
df.head()

,CGPA,PROFILE_SCORE,LPA
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [5]:
## Now the next imp part , importing the keras library
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [6]:
## Now storing object into variable
model = Sequential()
model.add(Dense(2,activation='sigmoid', input_dim=2)) ## This is the input layer 
model.add(Dense(1,activation='sigmoid'))
import warnings
warnings.filterwarnings('ignore')

D:\Anaconda\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.get_weights()

[array([[ 0.69931424, -0.673348  ],
        [ 0.20645905, -0.6093368 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.07585859],
        [0.00776815]], dtype=float32),
 array([0.], dtype=float32)]

In [9]:
new_weights=[np.array([[0.1,0.1],
                     [0.1,0.1]], dtype=np.float32),
            np.array([0.,0.], dtype=np.float32),
            np.array([[0.1],[0.1]], dtype=np.float32),
            np.array([0.], dtype=np.float32)]

In [10]:
model.set_weights(new_weights)

In [11]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss="binary_crossentropy", optimizer=optimizer)

In [13]:
model.fit(df.iloc[:,0:-1].values, df['LPA'].values, epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: -0.1612
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: -0.2224
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: -0.2859
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: -0.3421
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: -0.4089 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: -0.4707
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: -0.5296
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: -0.5946 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: -0.6562
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: -0.7163
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: -0.7760
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: -0.8395
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: -0.9049
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: -0.9662
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -1.0278 
Epoch 16/75
4/4 

In [14]:
model.get_weights()

[array([[0.2979982 , 0.2979982 ],
        [0.28741303, 0.28741303]], dtype=float32),
 array([0.19429973, 0.19429973], dtype=float32),
 array([[0.39952174],
        [0.39952174]], dtype=float32),
 array([0.2897425], dtype=float32)]